Avalanche4.0/Avalanche4.0/Controllers/TransactionController.cs
using AvalancheChain3._0.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Context;
using WebApplication2.Models;
using WebApplication2.Services;

namespace WebApplication2.Controllers
{
    public class TransactionController : Controller
    {
        TransactionService ts = new TransactionService();
        UserService us = new UserService();
        // GET: Transaction
        public ActionResult Index()
        {
            User user = us.GetUser((int)Session["UserId"]);
            ViewBag.User = "UserId: "+Convert.ToString(user.UserId)+"  Name: "+user.Name;
            ViewBag.TransactionCount = "TransactionCount: " + Convert.ToString(user.transactioncount);
            List<Transaction> transactions = ts.GetUsersTransactions((int)Session["UserId"]);
                return View(transactions);   
        }

        // GET: Transaction/Details/5
        public ActionResult Details(int id)
        {
            return View(ts.GetTransaction(id));
        }
  
        // GET: Transaction/Create
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Read()
        {
            return View();
        }
       

        [HttpPost]
        public ActionResult Read(Transaction transaction)
        {
            try
            {
                HashingId hi = new HashingId();
                transaction.TransactionId = hi.rehash(transaction.Hash);
                if (ts.GetTransaction(transaction.TransactionId) != null)
                {
                    Session["TransactionId"] = transaction.TransactionId;
                    return RedirectToAction("ReadedTransaction", new { id = transaction.TransactionId });

                }
                else
                {
                    ModelState.AddModelError("ReadError", "Transaction with this hash does not exist");//poczytaj o tym
                    return View();
                }
            }
            catch(Exception e)
            {
                return View();
            }
        }

        public ActionResult ReadedTransaction(int id)
        {
            return View(ts.GetTransaction(id));
        }
     
        [HttpPost]
        public ActionResult ReadedTransaction(Transaction transaction)
        {
            try
            {
                HashingId hi = new HashingId();
                transaction.TransactionId = hi.rehash(transaction.Hash);
                User user = us.GetUser((int)Session["UserId"]);
                Transaction trans = ts.GetTransaction(transaction.TransactionId);
                ts.UseTransaction(trans, user);
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                ModelState.AddModelError("PermisionsError", e.Message);
                return View();
            }
        }

        // POST: Transaction/Create
        [HttpPost]
        public ActionResult Create(Transaction transaction)
        {
            try
            {
                int num = (int)Session["UserId"];
                transaction.ProducerId = num;
                ts.AddNewTransaction(transaction);
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                return View();
            }
        }

        // GET: Transaction/Edit/5
        public ActionResult Edit(int id)
        {
            Transaction transaction = ts.GetTransaction(id);
            return View(transaction);
        }

        // POST: Transaction/Edit/5
        [HttpPost]
        public ActionResult Edit(Transaction transaction)
        {
            try
            {
                User user = us.GetUser((int)Session["UserId"]);
                ts.EditTransaction(transaction, transaction,user);
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                ModelState.AddModelError("StatusError", e.Message);//poczytaj o tym

                return View();
            }
        }

        // GET: Transaction/Delete/5
        public ActionResult Delete(int id)
        {
            return View(ts.GetTransaction(id));
        }

        // POST: Transaction/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                ts.DeleteTransaction(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Avalanche4.0/Avalanche4.0/Views/Transaction/Create.cshtml
@model WebApplication2.Models.Transaction

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prodactionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prodactionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prodactionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.shelfLife, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.shelfLife, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.shelfLife, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.info, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.info, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.info, "", new { @class = "text-danger" })
            </div>
        </div>

    

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Avalanche4.0/Avalanche4.0/Views/Transaction/Delete.cshtml
@model WebApplication2.Models.Transaction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.info)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.info)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProducerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProducerId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Avalanche4.0/Avalanche4.0/Views/Transaction/Details.cshtml
@model WebApplication2.Models.Transaction

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prodactionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prodactionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.shelfLife)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.shelfLife)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.info)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.info)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProducerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProducerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentOwnerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentOwnerId)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TransactionId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Avalanche4.0/Avalanche4.0/Views/Transaction/Edit.cshtml
@model WebApplication2.Models.Transaction

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TransactionId)

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessage("StatusError", new { @style = "color:red" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prodactionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prodactionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prodactionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.shelfLife, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.shelfLife, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.shelfLife, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.info, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.info, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.info, "", new { @class = "text-danger" })
            </div>
        </div>

   

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Avalanche4.0/Avalanche4.0/Views/Transaction/Index.cshtml
@model IEnumerable<WebApplication2.Models.Transaction>


<p>
    @Html.TextBox("User")
</p>
<p>
    @Html.TextBox("TransactionCount")
</p>
<p>
    @Html.ActionLink("Read new", "Read")
</p>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Hash)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.info)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Hash)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.info)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.TransactionId }) |
                @Html.ActionLink("Details", "Details", new { id = item.TransactionId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.TransactionId })
            </td>
        </tr>
    }

</table>

Avalanche4.0/Avalanche4.0/Views/Transaction/Read.cshtml
@model WebApplication2.Models.Transaction

@{
    ViewBag.Title = "Read";
}

<h2>Read</h2>



<div id="Read">
    @using (Html.BeginForm("Read", "Transaction", FormMethod.Post))
    {
    <div class="form-group">
        @Html.LabelFor(model => model.Hash, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Hash, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("ReadError", new { @style = "color:red" })
          
        </div>
    </div>
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="name" value="Read" />

                </td>
            </tr>
    }
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Avalanche4.0/Avalanche4.0/Views/Transaction/ReadedTransaction.cshtml
@model WebApplication2.Models.Transaction


@{
    ViewBag.Title = "ReadedTransaction";
}

<h2>ReadedTransaction</h2>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prodactionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prodactionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.shelfLife)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.shelfLife)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.info)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.info)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProducerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProducerId)
        </dd>

    </dl>
</div>
<div id="Use">
    @using (Html.BeginForm("ReadedTransaction", "Transaction", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Hash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hash, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("PermisionsError", new { @style = "color:red" })
            </div>
        </div>
        <tr>
            <td></td>
            <td>
                <input type="submit" name="name" value="UseTransaction" />

            </td>
        </tr>
    }
</div>
<p>
   
    @Html.ActionLink("Back to List", "Index")
</p>